project:
  type: website

website:
  title: "Data Visualization (WQ25)"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - sidebar:slides
      - text: "Schedule"
        file: schedule.qmd
      - sidebar:assignments
      - sidebar:finalproject
      - about.qmd
      
  sidebar:
    - id: slides
      title: "Slides"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - 01-week1-workbook.qmd
        - 01-week1-slides.qmd
        - 02-week2-workbook.qmd
        - 02-week2-slides.qmd
        - 03-week3-workbook.qmd
        - 03-week3-slides.qmd
        - 04-week4-workbook.qmd
        - 04-week4-slides.qmd
        - 05-week5-workbook.qmd
        - 05-week5-slides.qmd
        - 06-week6-workbook.qmd
        - 06-week6-slides.qmd
        - 07-week7-workbook.qmd
        - 07-week7-slides.qmd
        - 08-week8-workbook.qmd
        - 08-week8-slides.qmd
        - 09-week9-workbook.qmd
        - 09-week9-slides.qmd
        # - 10-week10-slides.qmd
        # - 10-week10-workbook.qmd
        
    - id: assignments
      title: "Problem Sets"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - ps1.qmd
        - ps1-solutions.qmd
        - ps2.qmd
        - ps2-solutions.qmd
        - ps3.qmd
        - ps3-solutions.qmd
        - ps4.qmd
        
    - id: finalproject
      title: "Final Project"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - final-project-proposal.qmd
        - final-project-presentation.qmd
        - final-project-paper.qmd
        - final-project-rubric.qmd

format:
  html:
    theme: [cosmo, custom-styles.scss]
    css: styles.css
    toc: true

editor: visual

