---
title: "Final Project Paper Rubric"
subtitle: "PSC290 - Data Visualization, WQ25"
author: "Emorie D Beck"
institution: "University of California, Davis"
format: pdf
---

-   Due at 11:59 PM PST on March **20**, 2025 on Canvas

| Section / Description | Points |
|--------------------------------------------------------|----------------|
| **Background**: Describe the background / impetus for your visualization. What makes your research question important and why should I care? 1-2 paragraphs is sufficient in most cases. | 4 points |
| **Research Questions**: Clearly state the research question(s) you are answering in your visualization and hypothesis(es), if any. | 4 points |
| **Method**: Short description of (1) Participants, (2) Measures, (3) Procedure, (4) Analytic Plan. Include each section (or others not listed here) as is applicable for your project. This does not need to be a full Method section, but it helps me know things about the range of scales, details like the number of trials, etc., which can help me in evaluating your visualization. There is no minimum of maximum length, but my guess is no less than 2-3 paragraphs. | 4 points |
| **Results**: Write the paragraph (or paragraphs) that would refer to your viusalization as if you were putting it in a manuscript. Be sure to make reference to the figure and provide necessary description to make clear why it's relevant to your results and/or answers your research question | 4 points |
| **Visualization**: Include your viusalization and figure caption. This will be graded for its connection to the research question and overall clarity. | 4 points |
| **Connection to Class Concepts**: Connect your visualization(s) to topics learned throughout the course. Did you use color to leverage preattentive processing? Grouping? Movement? Shape? Content can come from any part of the course. Please cite the reading or source you use as it will help me evaluate different readings used throughout the course. | 10 points |
| **Total** | **30 points** |
