---
title: "Schedule"
---

Course Schedule

Note: Course schedule is subject to change without notice.

+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **1**  | 01/08/2025 | [*Discussion*]{.underline}: Intro to Data Viz                                                                                                                                                                                                                                                                                             | 2 viz (any) + 2 paragraph response due at 12:00 PM on 01/08       |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Workshop*]{.underline}: Getting Situated in R & tidyverse                                                                                                                                                                                                                                                                               |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Readings:*]{.underline}                                                                                                                                                                                                                                                                                                                 |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Wilke](#0) Ch. 2, 29                                                                                                                                                                                                                                                                                                                 |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | <!-- -->                                                                                                                                                                                                                                                                                                                                  |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Healy](https://socviz.co/lookatdata.html#lookatdata) Ch. 1                                                                                                                                                                                                                                                                           |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Jones: Graphical Gaffes](https://docs.google.com/presentation/d/14zGLucWYnU6qQXzEfmpCuDi3YJ-fKqO3wZ7F1WX5iXk/edit#slide=id.g8283136367_0_0)                                                                                                                                                                                          |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **2**  | 01/15/2025 | [*Discussion*]{.underline}: Cognitive Perspectives on Data Visualization                                                                                                                                                                                                                                                                  | 2 viz + 2 paragraph response due at 12:00 PM on Tues. 01/14       |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Workshop*]{.underline}: Working with ggplot2                                                                                                                                                                                                                                                                                            |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Readings:*]{.underline}                                                                                                                                                                                                                                                                                                                 |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Kazakova (2021). The Psychology Behind Data Visualization Techniques.](https://medium.com/m/global-identity-2?redirectUrl=https%3A%2F%2Ftowardsdatascience.com%2Fthe-psychology-behind-data-visualization-techniques-68ef12865720)                                                                                                   |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Healey, C. G. (2007). Perception in visualization. Retrieved September 5, 2022](https://www.csc2.ncsu.edu/faculty/healey/PP/).                                                                                                                                                                                                       |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Franconeri, S. L., Padilla, L. M., Shah, P., Zacks, J. M., & Hullman, J. (2021). The science of visual data communication: What works. *Psychological Science in the public interest, 22*(3), 110-161.](https://files.de-1.osf.io/v1/resources/4fyaq/providers/osfstorage/61ddb0930b534b01514329d9?action=download&direct&version=1) |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/dn5kATeTvrONEwEZNiVRGAj0a6dq5-jXaUxL0nIHFmra8EQ-fVsKwz9_6N5xnWI-.pbZSq8Bq5UaHr_Xi?startTime=1736962229000)                                                                                                                                                                             |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **3**  | 01/22/2025 | [*Discussion*]{.underline}: Visualizing Proportions and Probability                                                                                                                                                                                                                                                                       | 2 viz (any) + 2 paragraph response due at 12:00 PM on Tues. 01/21 |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Workshop*]{.underline}: Should I Ever Use a Pie Chart?                                                                                                                                                                                                                                                                                  |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Readings:*]{.underline}                                                                                                                                                                                                                                                                                                                 |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   Wilke Ch. 10-11                                                                                                                                                                                                                                                                                                                       |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [Zoom recording](https://ucdavis.zoom.us/rec/share/xnKLjWrMEnhF6Jc_MPFgXVyxIpcPRWDPqQJgNHfNGRu-AL2Q4BezlXkA3G46Wjo.zQSxWzf3RgstLgRl)                                                                                                                                                                                                      |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **4**  | 01/29/2025 | [*Discussion*]{.underline}: Visualizing Differences and Associations                                                                                                                                                                                                                                                                      | 2 viz (any) + 2 paragraph response due at 12:00 PM on Tues. 01/28 |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Workshop*]{.underline}: Summarizing Models                                                                                                                                                                                                                                                                                              |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Readings:*]{.underline}                                                                                                                                                                                                                                                                                                                 |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   Wilke Ch. 12                                                                                                                                                                                                                                                                                                                          |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/x-8An8mt-ZSvQF6DxpHFzvNHYbwJZLJrstwpmc0rIotVG2BIlk1tWisrigQpethi.biztQuMjd6TLVIAy)                                                                                                                                                                                                     |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **5**  | 02/05/2025 | [*Discussion*]{.underline}: Visualizing Change                                                                                                                                                                                                                                                                                            | 2 viz (any) + 2 paragraph response due at 12:00 PM on Tues. 02/04 |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Workshop*]{.underline}: Trajectories and Times Series                                                                                                                                                                                                                                                                                   |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Readings:*]{.underline}                                                                                                                                                                                                                                                                                                                 |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Wilke](https://clauswilke.com/dataviz/) Ch. 13-14                                                                                                                                                                                                                                                                                    |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/MhEOUAjleDNc4B0_MfVFX15uSblUEvndBaj6tBmO2Ko5nBU-vsgYsrTEft6hxstg.3XT50e_PmduhaZHA)                                                                                                                                                                                                     |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **6**  | 02/12/2025 | [*Discussion*]{.underline}: Visualizing Uncertainty                                                                                                                                                                                                                                                                                       | 2 viz (any) + 2 paragraph response due at 12:00 PM on Tues. 02/11 |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Workshop*]{.underline}: Visualizing Uncertainty                                                                                                                                                                                                                                                                                         | **PROPOSALS DUE**                                                 |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Readings:*]{.underline}                                                                                                                                                                                                                                                                                                                 |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Padilla, Kay, & Hullman (2020). Visualizing Uncertainty](https://psyarxiv.com/ebd6r/download?format=pdf).                                                                                                                                                                                                                            |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   Wilke Ch. 16                                                                                                                                                                                                                                                                                                                          |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   Skim [Wilke](https://clauswilke.com/dataviz/) Ch. 7-9 (optional)                                                                                                                                                                                                                                                                      |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/Kv3sfmVkXEEhF1LV2sCEctMqUQhF7-rXI3b--XiFAXd4i1wyNvwgD8GUCqQtIAcR.DtTH_WofeXatwymC)                                                                                                                                                                                                     |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **7**  | 02/19/2025 | [*Discussion*]{.underline}: Piecing Visualizations Together                                                                                                                                                                                                                                                                               | 2 viz (any) + 2 paragraph response due at 12:00 PM on Tues. 02/18 |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Workshop*]{.underline}: Panel plots, cowplot, and more                                                                                                                                                                                                                                                                                  |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Readings:*]{.underline}                                                                                                                                                                                                                                                                                                                 |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Wilke](https://clauswilke.com/dataviz/) Ch. 21                                                                                                                                                                                                                                                                                       |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/Cg1ooqsKlg5ThafafCkSA-29OhzeA9uXkrdEXlSSggB6oInXP_u6xXvwOMNDZxmd.iJsIrZIlcqU2Ax10)                                                                                                                                                                                                     |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **8**  | 02/26/2025 | [*Discussion*]{.underline}: Polishing Visualizations                                                                                                                                                                                                                                                                                      | 2 viz (any) + 2 paragraph response due at 12:00 PM on Tues. 02/25 |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Workshop*]{.underline}:                                                                                                                                                                                                                                                                                                                 | **MEETINGS DUE**                                                  |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Readings:*]{.underline}                                                                                                                                                                                                                                                                                                                 |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   [Wilke](https://clauswilke.com/dataviz/) Ch. 17, 19, 23                                                                                                                                                                                                                                                                               |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | -   Skim [Wilke](https://clauswilke.com/dataviz/) 18, 22, 24-26                                                                                                                                                                                                                                                                           |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **9**  | 03/05/2025 | [*Discussion*]{.underline}: Interactive Visualizations                                                                                                                                                                                                                                                                                    | 2 viz (any) + 2 paragraph response due at 12:00 PM on Tues. 03/04 |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Workshop*]{.underline}: Getting Started in RShiny                                                                                                                                                                                                                                                                                       |                                                                   |
|        |            |                                                                                                                                                                                                                                                                                                                                           |                                                                   |
|        |            | [*Readings:*]{.underline}                                                                                                                                                                                                                                                                                                                 |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **10** | 03/12/2025 | In-Class Presentations                                                                                                                                                                                                                                                                                                                    |                                                                   |
+--------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
